# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quorum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cquorum.proto\x12\x06quorum\"1\n\x0cQuorumConfig\x12\t\n\x01N\x18\x01 \x01(\x05\x12\n\n\x02Nr\x18\x02 \x01(\x05\x12\n\n\x02Nw\x18\x03 \x01(\x05\"6\n\x12InitQuorumResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x07Request\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"N\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x32\xa5\x01\n\x06Quorum\x12@\n\nInitQuorum\x12\x14.quorum.QuorumConfig\x1a\x1a.quorum.InitQuorumResponse\"\x00\x12,\n\x05Write\x12\x0f.quorum.Request\x1a\x10.quorum.Response\"\x00\x12+\n\x04Read\x12\x0f.quorum.Request\x1a\x10.quorum.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quorum_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUORUMCONFIG._serialized_start=24
  _QUORUMCONFIG._serialized_end=73
  _INITQUORUMRESPONSE._serialized_start=75
  _INITQUORUMRESPONSE._serialized_end=129
  _REQUEST._serialized_start=131
  _REQUEST._serialized_end=168
  _RESPONSE._serialized_start=170
  _RESPONSE._serialized_end=248
  _QUORUM._serialized_start=251
  _QUORUM._serialized_end=416
# @@protoc_insertion_point(module_scope)
