# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import quorum_pb2 as quorum__pb2


class QuorumStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitQuorum = channel.unary_unary(
                '/quorum.Quorum/InitQuorum',
                request_serializer=quorum__pb2.QuorumConfig.SerializeToString,
                response_deserializer=quorum__pb2.InitQuorumResponse.FromString,
                )
        self.Write = channel.unary_unary(
                '/quorum.Quorum/Write',
                request_serializer=quorum__pb2.Request.SerializeToString,
                response_deserializer=quorum__pb2.Response.FromString,
                )
        self.Read = channel.unary_unary(
                '/quorum.Quorum/Read',
                request_serializer=quorum__pb2.Request.SerializeToString,
                response_deserializer=quorum__pb2.Response.FromString,
                )


class QuorumServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitQuorum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuorumServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitQuorum': grpc.unary_unary_rpc_method_handler(
                    servicer.InitQuorum,
                    request_deserializer=quorum__pb2.QuorumConfig.FromString,
                    response_serializer=quorum__pb2.InitQuorumResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=quorum__pb2.Request.FromString,
                    response_serializer=quorum__pb2.Response.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=quorum__pb2.Request.FromString,
                    response_serializer=quorum__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quorum.Quorum', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Quorum(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitQuorum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/quorum.Quorum/InitQuorum',
            quorum__pb2.QuorumConfig.SerializeToString,
            quorum__pb2.InitQuorumResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/quorum.Quorum/Write',
            quorum__pb2.Request.SerializeToString,
            quorum__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/quorum.Quorum/Read',
            quorum__pb2.Request.SerializeToString,
            quorum__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
