# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ex1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tex1.proto\x12\x03\x65x1\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\rHelloResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"D\n\rDelayResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\"\n\x07request\x18\x02 \x03(\x0b\x32\x11.ex1.HelloRequest2\xee\x01\n\x03\x65x1\x12\x33\n\nHelloWorld\x12\x11.ex1.HelloRequest\x1a\x12.ex1.HelloResponse\x12\x37\n\x0c\x43lientStream\x12\x11.ex1.HelloRequest\x1a\x12.ex1.DelayResponse(\x01\x12\x37\n\x0cServerStream\x12\x11.ex1.HelloRequest\x1a\x12.ex1.HelloResponse0\x01\x12@\n\x13\x42idirectionalStream\x12\x11.ex1.HelloRequest\x1a\x12.ex1.HelloResponse(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ex1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=18
  _HELLOREQUEST._serialized_end=46
  _HELLORESPONSE._serialized_start=48
  _HELLORESPONSE._serialized_end=79
  _DELAYRESPONSE._serialized_start=81
  _DELAYRESPONSE._serialized_end=149
  _EX1._serialized_start=152
  _EX1._serialized_end=390
# @@protoc_insertion_point(module_scope)
