# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speedtest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspeedtest.proto\x12\tspeedtest\"\x1f\n\x0cSpeedRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rSpeedResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2L\n\tSpeedTest\x12?\n\x04Test\x12\x17.speedtest.SpeedRequest\x1a\x18.speedtest.SpeedResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speedtest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPEEDREQUEST._serialized_start=30
  _SPEEDREQUEST._serialized_end=61
  _SPEEDRESPONSE._serialized_start=63
  _SPEEDRESPONSE._serialized_end=95
  _SPEEDTEST._serialized_start=97
  _SPEEDTEST._serialized_end=173
# @@protoc_insertion_point(module_scope)
